### ISSUE TITLE
Docs out of Date

### ISSUE THREAD

**Issue by SilentCicero** [jorgebucaran/hyperapp-router#101]
These docs are out of date with the module published. There is only Router and Route now available in the lib. Please warn people in the docs.

**Comment by jorgebucaran** [comment]
@SilentCicero Thanks for pointing that out. I don't have time to maintain this module at this particular moment in time, so everything is "on hold" until I am able to get back to it. I am, however, happy to merge a PR that adds such warning to the docs.

Thanks!
