### ISSUE TITLE
Refresh browser app crash

### ISSUE THREAD

**Issue by Vibing** [jorgebucaran/hyperapp-router#102]
The same with: https://github.com/jorgebucaran/hyperapp-router/issues/80

What should I do in the code?

**Comment by jorgebucaran** [comment]
@Vibing Do you have (or could you make) a pen or a CodeSandBox that we can work with?

**Comment by Vibing** [comment]
@jorgebucaran Thank you for answering my question. I think the problem I encountered might be the same as the [online demo](http://hyperapp-router.surge.sh). 

If I type `http://hyperapp-router.surge.sh` in the address bar and jump to` http://hyperapp-router.surge.sh/test` by clicking on the route, it is ok. 
But I typed `http://hyperapp-router.surge.sh/test` directly and it went wrong.

By route:
![1](https://user-images.githubusercontent.com/10387532/55446123-f1473b00-55f0-11e9-9a14-454772de50b9.png)

Direct access address：
![2](https://user-images.githubusercontent.com/10387532/55446135-fb693980-55f0-11e9-9649-396c0d81c913.png)

My English is not good, please forgive me.😄

**Comment by jorgebucaran** [comment]
@Vibing I found a few links that may help you. If you are using:

- Surge <<https://surge.sh/help/adding-a-200-page-for-client-side-routing>>
- Netlify <<https://www.netlify.com/docs/redirects>>
- GitHub Pages via a `404.html` with redirects <[rafrex/spa-github-pages/blob/gh-pages/404.html](https://github.com/rafrex/spa-github-pages/blob/gh-pages/404.html)>

If you are serving an `index.html` with your app by yourself, you have more power. 

- Express <<https://stackoverflow.com/questions/26349497/node-express-with-static-html-how-to-route-all-requests-to-index-html>>
- Rails <<https://stackoverflow.com/questions/5631145/routing-to-static-html-page-in-public>>
