### ISSUE TITLE
Supports all-match feature on TypeScript

### ISSUE THREAD

**Issue by babie** [jorgebucaran/hyperapp-router#98]
On JaveScript, &lt;Route&gt; has not necessary a `path` prop. In case of no `path` prop, &lt;Route&gt; matches all path.
But on TypeScript, &lt;Route&gt; must have a `path` prop on current code.

Because it defined in `index.d.ts`:
```ts
interface RouteProps<P> {
  parent?: boolean;
  path: string;
  location?: Location;
  render: (props: RenderProps<P>) => VNode<RenderProps<P>>;
}
```

**Comment by jorgebucaran** [comment]
Implemented by #99.
